# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [59]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [60]:
print(np.__version__)
print(np.__config__)

1.21.3
<module 'numpy.__config__' from 'C:\\Users\\KIIT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\__config__.py'>


#### 3. Create a null vector of size 10

In [61]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [62]:
arr=np.array([1,2,3])
arr.itemsize

4

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [63]:
# python -c "import numpy; numpy.info(numpy.add)"

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [64]:
arr= np.zeros(10)
arr[4]= 1
print (arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [65]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [66]:
A = np.array([1,2,3])
print (A[::-1])

[3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [67]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [68]:
W=np.nonzero([1,2,0,0,4,0])
print(W)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [69]:
X=np.eye(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [70]:
X=np.random.uniform((3,3,3))
print(X)

[2.54059242 2.06482041 1.14691345]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [71]:
arr = np.random.random((10,10))
minval, maxval = arr.min(), arr.max()
print(minval, maxval)

0.0036254441938342596 0.9338090284363249


#### 14. Create a random vector of size 30 and find the mean value

In [72]:
arr=np.random.random(10)
print(arr.mean())

0.5536426479898091


#### 15. Create a 2d array with 1 on the border and 0 inside

In [73]:
arr= np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [74]:
arr = np.ones((3,3))
print("Original array:")
print(arr)
print("Adding 0 on the border and 1 inside in the array")
arr=np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Adding 0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [75]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [76]:
arr = np.random.rand(5,5)
print(arr)
d= np.diag(arr, k=-1)
id = np.isin(arr, d).nonzero()
arr[id] = np.array([1,2,3,4], dtype = float)
print()
print(arr)

[[0.20907997 0.70635764 0.48640296 0.96112208 0.10449264]
 [0.8592468  0.56854009 0.42352305 0.90533545 0.20356123]
 [0.61840064 0.45938118 0.88309398 0.33378845 0.41999554]
 [0.20866537 0.31209654 0.08240441 0.49638989 0.98741932]
 [0.65192218 0.56309712 0.19771885 0.48788606 0.90005283]]

[[0.20907997 0.70635764 0.48640296 0.96112208 0.10449264]
 [1.         0.56854009 0.42352305 0.90533545 0.20356123]
 [0.61840064 2.         0.88309398 0.33378845 0.41999554]
 [0.20866537 0.31209654 3.         0.49638989 0.98741932]
 [0.65192218 0.56309712 0.19771885 4.         0.90005283]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [77]:
arr = np.ones((3,3))
print("Checkerboard pattern:")
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [78]:
print (np.unravel_index(100,(6,7,8)))

(1, 5, 4)
