# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)
print(np.__config__)

1.21.3
<module 'numpy.__config__' from 'C:\\Users\\KIIT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\__config__.py'>


#### 3. Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [5]:
arr=np.array([1,2,3])
arr.itemsize

4

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
# python -c "import numpy; numpy.info(numpy.add)"

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
arr= np.zeros(10)
arr[4]= 1
print (arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [9]:
A = np.array([1,2,3])
print (A[::-1])

[3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [11]:
W=np.nonzero([1,2,0,0,4,0])
print(W)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [12]:
X=np.eye(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [13]:
X=np.random.random((3,3,3))
print(X)

[[[0.5614068  0.18038321 0.92603314]
  [0.66249437 0.92666783 0.99954125]
  [0.96139207 0.91136947 0.94080698]]

 [[0.18552921 0.85432199 0.11447454]
  [0.65069262 0.24662192 0.36130428]
  [0.88644262 0.72416186 0.92641715]]

 [[0.52062949 0.48511913 0.77936949]
  [0.22792689 0.54515762 0.31228979]
  [0.18618023 0.91793809 0.74158282]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
arr = np.random.random((10,10))
minval, maxval = arr.min(), arr.max()
print(minval, maxval)

0.01281895775061781 0.9987961048410801


#### 14. Create a random vector of size 30 and find the mean value

In [15]:
arr=np.random.random(10)
print(arr.mean())

0.5943855161625439


#### 15. Create a 2d array with 1 on the border and 0 inside

In [16]:
arr= np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [17]:
arr = np.ones((3,3))
print("Original array:")
print(arr)
print("Adding 0 on the border and 1 inside in the array")
arr=np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Adding 0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [19]:
arr = np.random.rand(5,5)
print(arr)
d= np.diag(arr, k=-1)
id = np.isin(arr, d).nonzero()
arr[id] = np.array([1,2,3,4], dtype = float)
print()
print(arr)

[[0.52778608 0.82526205 0.36046568 0.83748105 0.6359284 ]
 [0.39946582 0.69479026 0.06555762 0.47322019 0.03062403]
 [0.93315254 0.09790433 0.95774798 0.2469656  0.24179623]
 [0.65614396 0.44330672 0.01780741 0.85462493 0.11009908]
 [0.98068836 0.31634061 0.02133193 0.66580482 0.53024006]]

[[0.52778608 0.82526205 0.36046568 0.83748105 0.6359284 ]
 [1.         0.69479026 0.06555762 0.47322019 0.03062403]
 [0.93315254 2.         0.95774798 0.2469656  0.24179623]
 [0.65614396 0.44330672 3.         0.85462493 0.11009908]
 [0.98068836 0.31634061 0.02133193 4.         0.53024006]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [20]:
arr = np.ones((3,3))
print("Checkerboard pattern:")
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
print (np.unravel_index(100,(6,7,8)))

(1, 5, 4)
